version: '3'
services:
  impala:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/impala:2.8.0-cdh5.11.1
    networks:
    - parrot
    external_links:
    - hadoop
    - hive
    volumes:
    - impala_logs:/opt/impala/be/build/release/logs
    ports:
    - 21000:21000
    - 21050:21050
    - 25000:25000
    - 25010:25010
    - 25020:25020
volumes:
  impala_logs: null
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
