version: "3"

services:

    impala:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/impala:2.8.0-cdh5.11.1
        networks:
            - hadoop
        external_links:
            - hadoop
            - hive
        volumes:
            - impala_logs:/opt/impala/be/build/release/logs
        ports:            
            - "21000:21000"
            - "21050:21050"
            - "22000:22000"
            - "23000:23000"
            - "24000:24000"
            - "25010:25010"
            - "26000:26000"
            - "28000:28000"

volumes:
    impala_logs:

networks:
    default:
      external:
        name: hadoop
    hadoop:
        driver: bridge
